### ISSUE TITLE
Any chance to make it work with KiCad 7?

### ISSUE THREAD

**Issue by makeitsquare** [0xffox/pcbnew-array-align#2]
I tried your plugin with KiCad 7.08 on MacOS, but got the following error:

Exception on python action plugin code

Traceback (most recent call last):

File "/Users/m/Documents/KiCad/7.0/scripting/plugins/array_align/array_align_action.py", line 42, in Run
self._alignElems(

File "/Users/m/Documents/KiCad/7.0/scripting/plugins/array_align/array_align_action.py", line 107, in _alignElems
origins = self._getOrigins(selected, (cols-1)*hgap, (rows-1)*vgap)

File "/Users/m/Documents/KiCad/7.0/scripting/plugins/array_align/array_align_action.py", line 54, in _getOrigins
center = reduce(lambda x, y: x + y.GetPosition(), elems, pcbnew.wxPoint(0, 0))

File "/Users/m/Documents/KiCad/7.0/scripting/plugins/array_align/array_align_action.py", line 54, in <lambda>
center = reduce(lambda x, y: x + y.GetPosition(), elems, pcbnew.wxPoint(0, 0))

TypeError: unsupported operand type(s) for +: 'wxPoint' and 'VECTOR2I'

**Comment by bjsi** [comment]
Got GPT to rewrite and fix the error

```
# array_align_action.py
import os
from functools import reduce

import pcbnew
import wx

from .ui.dialog import ArrayDialog


# ---------- helpers to bridge KiCad versions (wxPoint vs VECTOR2I) ----------
def _Point(x, y):
    """Create a KiCad point using VECTOR2I on v9+, wxPoint on older."""
    cls = getattr(pcbnew, "VECTOR2I", None)
    if cls is None:
        cls = pcbnew.wxPoint
    return cls(int(x), int(y))

def _pos(obj):
    """Return (x, y) position as plain ints from any BOARD_ITEM."""
    p = obj.GetPosition()
    # pcbnew.VECTOR2I / wxPoint both expose x,y
    return int(p.x), int(p.y)

def _set_pos(obj, x, y):
    """Set absolute position when possible; otherwise move by delta."""
    pt = _Point(x, y)
    if hasattr(obj, "SetPosition"):
        obj.SetPosition(pt)
        return
    # Fallback: compute delta and Move() if available
    try:
        cx, cy = _pos(obj)
        dx, dy = x - cx, y - cy
        if hasattr(obj, "Move"):
            obj.Move(_Point(dx, dy))
    except Exception:
        # Silently ignore items we can't move explicitly (tracks, etc.)
        pass


class ArrayAlignAction(pcbnew.ActionPlugin):
    def defaults(self):
        self.name = "Array Align"
        self.category = "align"
        self.description = "Align selected elements in the grid"
        self.show_toolbar_button = True
        self.icon_file_name = os.path.join(os.path.dirname(__file__), 'icon.png')

    # ---- units helpers ----
    def _getFromUnits(self, user_units):
        # KiCad user unit codes:
        # 0 = inches (mils), 1 = mm, 5 = mils (minch)
        units = {
            0: lambda u: pcbnew.FromMils(u),           # inches dialog, value is in mils in KiCad API
            1: lambda u: pcbnew.FromMM(u),
            5: lambda u: pcbnew.FromMils(u / 1000.0),  # "minch" = thousandth of an inch
        }
        return units.get(user_units, units[1])

    def _getUnitName(self, user_units):
        names = {0: 'inch', 1: 'mm', 5: 'minch'}
        return names.get(user_units, 'mm')

    # ---- core run ----
    def Run(self):
        user_units = pcbnew.GetUserUnits()
        fromUnits = self._getFromUnits(user_units)

        dlg = ArrayDialog(user_units=self._getUnitName(user_units))
        dlg.Center()
        if dlg.ShowModal() == wx.ID_OK:
            params = dlg.getValues()
            try:
                self._alignElems(
                    selection_type=params['ch_elem_type'],
                    origin_type=params['ch_origin_type'],
                    rows=int(params['tx_rows']),
                    cols=int(params['tx_cols']),
                    hgap=fromUnits(float(params['tx_h_gap'])),
                    vgap=fromUnits(float(params['tx_v_gap']))
                )
            except Exception as e:
                wx.MessageBox(f"Array Align error:\n{e}", "Array Align", wx.OK | wx.ICON_ERROR)
        dlg.Destroy()

    # ---- geometry helpers ----
    def _getOrigins(self, elems, new_width, new_height):
        # Gather all positions as ints
        xs, ys = [], []
        for m in elems:
            x, y = _pos(m)
            xs.append(x); ys.append(y)

        left, right = min(xs), max(xs)
        top, bot    = min(ys), max(ys)
        width, height = abs(right - left), abs(bot - top)

        # Origins for different anchor choices
        return {
            0: _Point(  # center
                left + width / 2 - new_width / 2,
                top  + height / 2 - new_height / 2
            ),
            1: _Point(left, top),  # top-left
            2: _Point(left, top + height - new_height),  # bottom-left
            3: _Point(left + width - new_width, top),     # top-right
            4: _Point(left + width - new_width, top + height - new_height),  # bottom-right
        }

    def _sortElems(self, elems, rows, cols):
        # Sort by Y (top to bottom), then within each row by X (left to right)
        elems = sorted(elems, key=lambda x: _pos(x)[1])
        for r in range(rows):
            s, e = r * cols, (r + 1) * cols
            elems[s:e] = sorted(elems[s:e], key=lambda x: _pos(x)[0])
        return elems

    # ---- main align ----
    def _alignElems(self, selection_type=0, origin_type=1, rows=1, cols=1, hgap=0, vgap=0):
        board = pcbnew.GetBoard()

        selection_types = {
            0: board.GetFootprints,  # modules/footprints
            1: board.GetDrawings,    # drawings/graphics
            2: board.GetPads,        # individual pads
            3: board.GetTracks,      # segments/vias (best effort)
        }

        getter = selection_types.get(selection_type, board.GetFootprints)
        selected = [m for m in getter() if m.IsSelected()]
        if not selected:
            return

        selected = self._sortElems(selected, rows, cols)
        origins = self._getOrigins(selected, (cols - 1) * hgap, (rows - 1) * vgap)

        # Place into the grid
        origin_pt = origins.get(origin_type, origins[1])
        ox, oy = int(origin_pt.x), int(origin_pt.y)

        for r in range(rows):
            for c in range(cols):
                idx = r * cols + c
                if idx >= len(selected):
                    break
                nx = ox + int(c * hgap)
                ny = oy + int(r * vgap)
                _set_pos(selected[idx], nx, ny)

        pcbnew.Refresh()
```
